version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
